/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// Remove old assets from previous versions
try {
  cleanupOutdatedCaches();
} catch (e) {
  console.error('Workbox cleanupOutdatedCaches failed:', e);
}

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Force immediate activation
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Initialize Firebase with environment variables
try {
  const firebaseConfig = {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: import.meta.env.VITE_FIREBASE_APP_ID
  };

  if (firebaseConfig.apiKey) {
    const app = initializeApp(firebaseConfig);
    const messaging = getMessaging(app);

    onBackgroundMessage(messaging, (payload) => {
      console.log('🔥🔥 [sw.ts] BACKGROUND MESSAGE RECEIVED:', JSON.stringify(payload));
      
      const notificationTitle = payload.notification?.title || 'Check-in Alert';
      const notificationOptions: any = {
        body: payload.notification?.body || 'Your safety check-in is requested.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [200, 100, 200],
        requireInteraction: true,
        data: payload.data,
        actions: payload.data?.action === 'checkin' ? [
          {
            action: 'checkin-action',
            title: 'I\'m Good (Check-in Now)',
            icon: '/icon.svg'
          }
        ] : []
      };

      console.log('📢 [sw.ts] Attempting to showNotification:', notificationTitle);
      return self.registration.showNotification(notificationTitle, notificationOptions)
        .then(() => console.log('✅ [sw.ts] showNotification SUCCESS'))
        .catch(err => console.error('❌ [sw.ts] showNotification ERROR:', err));
    });

    // Handle notification click
    self.addEventListener('notificationclick', (event: any) => {
      event.notification.close();

      if (event.action === 'checkin-action') {
        // Option 1: Open the app and let it handle the check-in
        const urlToOpen = new URL('/', self.location.origin).href;
        
        event.waitUntil(
          self.clients.matchAll({ type: 'window', includeUncontrolled: true })
            .then((windowClients) => {
              for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                  return (client as any).focus().then((focusedClient: any) => {
                    // Send a message to the focused client to trigger check-in
                    focusedClient.postMessage({
                      type: 'TRIGGER_CHECKIN'
                    });
                  });
                }
              }
              if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen + '?action=checkin');
              }
            })
        );
      } else {
        // Just focus/open the app for regular clicks
        event.waitUntil(
          self.clients.matchAll({ type: 'window', includeUncontrolled: true })
            .then((windowClients) => {
              if (windowClients.length > 0) {
                return (windowClients[0] as any).focus();
              }
              if (self.clients.openWindow) {
                return self.clients.openWindow('/');
              }
            })
        );
      }
    });
  } else {
    console.warn('[sw.ts] Firebase config missing, background messaging disabled.');
  }
} catch (err) {
  console.error('[sw.ts] Firebase initialization failed:', err);
}
